---
-
  hosts : all
  user : ansible
  gather_facts : true 


  vars : 
    motd_centos : "Example data only for Centos Machines \n"
    motd_ubuntu : "Example data only for Ubuntu Machines \n"

  tasks :
    - name : Configure a motd for Centos
      copy :
        content : " {{ motd_centos }}"
        dest : "/tmp/motd"
      when : ansible_distribution == "CentOS"
    
    - name : Configure a motd for Ubuntu
      copy :
        content : " {{ motd_ubuntu }}"
        dest : "/tmp/motd"
      when : ansible_distribution == "Ubuntu"

...



